name: CICD Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
    DOTNETVERSION: 8.0.x

jobs:  
  buildAndroid:
    runs-on: macos-14
    
    steps:

      # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
      # github docs for installing cert and provisioning profile
      - uses: actions/checkout@v2
      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'

      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

       # Store Android Signing Keystore and password in Secrets using base64 encoding
      # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil
      # commandline util to encode to base64 on windows
      - name: Extract Android signing key from env
        shell: bash
        run: |
            echo "${{ secrets.RELEASE_KEYSTORE }}" > encrypted.keystore
            base64 -d -i encrypted.keystore -o decrypted.keystore

      - name: Restore nuget packages
        run: |
          dotnet restore GitHubActionsMAUI.sln      
      
      - name: Build Android App
        shell: bash
        run: |
            dotnet publish GitHubActionsMAUI/GitHubActionsMAUI.csproj
            -c:Release
            -f:net8.0-android 
            /p:AndroidPackageFormats=aab 
            /p:AndroidKeyStore=true 
            /p:AndroidSigningKeyStore="decrypted.keystore"
            /p:AndroidSigningKeyAlias="${{ secrets.KEY_ALIAS }}"
            /p:AndroidSigningKeyPass="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}"
            /p:AndroidSigningStorePass="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}"
            --no-restore

      - name: List files in the build directory
        run: ls -R GitHubActionsMAUI/bin/Release/
   

        # # check android SDK paths etc in installed VM : https://github.com/actions/virtual-environments#available-environments
      # - name: Sign dev build
      #   shell: bash
      #   run: 
      #     jarsigner -keystore decrypted.keystore -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar GitHubActionsMAUI/bin/Release/net8.0-android/com.unizite.app-Signed.aab GitHubActionsMAUI/bin/Release/net8.0-android/publish/com.unizite.app-Signed.aab release

      - uses: actions/upload-artifact@v2
        with:
            name: artifacts-android
            path: |
              GitHubActionsMAUI/bin/Release/net8.0-android/publish/com.unizite.app-Signed.aab
