name: CI

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - custom-event

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, world!"
